domestic.standard.base=13
domestic.standard.perKg=1.5

international.express.base=30
international.express.perKg=5.5

international.standard.base=22
international.standard.perKg=4.5

domestic.express.base=20
domestic.express.perKg=4.5